# -*- coding: utf-8 -*-
"""ConverterPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhjLAg7TQ6pOro7ON1me7xns8u1ke2R5
"""

from datetime import datetime


class Banco:
    def __init__(self):
        self._nome = ""
        self._codigoBACEN = ""

    @property
    def Nome(self):
        return self._nome.upper()

    @Nome.setter
    def Nome(self, value):
        self._nome = value

    @property
    def CodigoBACEN(self):
        return self._codigoBACEN

    @CodigoBACEN.setter
    def CodigoBACEN(self, value):
        if value is None or value == "":
            raise ValueError("O Código BACEN não pode ser nulo ou vazio.")
        self._codigoBACEN = value


class Transacao:
    def __init__(self):
        self._valor = 0
        self.Data = None
        self.Tipo = ""

    @property
    def Valor(self):
        return self._valor

    @Valor.setter
    def Valor(self, value):
        if value > 0:
            self._valor = value
        else:
            raise ValueError("O valor da transação deve ser maior que zero.")



class ContaBancaria:
    def __init__(self):
        self.Agencia = ""
        self.NumeroConta = ""
        self.Saldo = 0.0



if __name__ == "__main__":

    meuBanco = Banco()
    meuBanco.Nome = "Banco do Brasil"
    meuBanco.CodigoBACEN = "001"


    minhaTransacao = Transacao()
    minhaTransacao.Valor = 250.00
    minhaTransacao.Data = datetime.now()
    minhaTransacao.Tipo = "PIX"

    CoontaBancaria = ContaBancaria()

    print("    REGISTRO BACEN    ")
    print("Banco:", meuBanco.Nome)
    print("Código:", meuBanco.CodigoBACEN)
    print("----------------------")
    print("Tipo:", minhaTransacao.Tipo)
    print("Valor:", minhaTransacao.Valor)
    print("Data:", minhaTransacao.Data)